export const STRINGS = {
  header: {
    searchPlaceholder: 'Search stems, bouquets, arrangements...',
    searchShortcut: '⌘K',
    orderPrefix: 'Order',
  },
  notificationsPopover: {
    title: 'Notifications',
    markAllRead: 'Mark all as read',
    viewMore: 'View all notifications',
    empty: 'You’re all caught up.',
  },
  notificationsPage: {
    title: 'Notifications',
    subtitle: 'Everything happening at the counter, in one place.',
    markAllRead: 'Mark all as read',
    empty: 'No notifications yet.',
    unreadBadge: 'unread',
  },
  notificationType: {
    order: 'Order',
    stock: 'Inventory',
    customer: 'Customer',
    system: 'System',
  },
  authLayout: {
    tagline: 'Run your counter, not your paperwork.',
  },
  loginPage: {
    title: 'Welcome back',
    subtitle: 'Sign in to open the counter.',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    submit: 'Sign in',
    noAccount: 'New to Marigold & Vine?',
    signUpLink: 'Create an account',
    demoHint: 'Demo mode — any email and a 6+ character password will work.',
    emailRequired: 'Enter a valid email address.',
    passwordRequired: 'Password must be at least 6 characters.',
    welcomeToast: 'Welcome back, {name}.',
  },
  signUpPage: {
    title: 'Create your account',
    subtitle: 'Set up your shop on Marigold & Vine.',
    name: 'Full name',
    namePlaceholder: 'e.g. Jamie Lin',
    storeName: 'Store name',
    storeNamePlaceholder: 'e.g. Blossom & Co.',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    passwordPlaceholder: 'Create a password',
    submit: 'Create account',
    haveAccount: 'Already have an account?',
    loginLink: 'Sign in',
    nameRequired: 'Name is required.',
    storeNameRequired: 'Store name is required.',
    emailRequired: 'Enter a valid email address.',
    passwordRequired: 'Password must be at least 6 characters.',
    welcomeToast: 'Account created — welcome, {name}.',
  },
  forgotPasswordPage: {
    title: 'Reset your password',
    subtitle: 'Enter your email and we’ll send you a reset link.',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    submit: 'Send reset link',
    emailRequired: 'Enter a valid email address.',
    backToLogin: 'Back to sign in',
    successTitle: 'Check your email',
    successMessage: 'If an account exists for {email}, a reset link is on its way.',
  },
  userMenu: {
    myOrders: 'My Orders',
    customers: 'Customers',
    reports: 'Reports',
    settings: 'Settings',
    logOut: 'Log out',
    signedOut: 'You’ve been signed out.',
  },
  productGrid: {
    title: 'Bouquets & Arrangements',
    itemsSuffix: 'items',
    filter: 'Filter',
    empty: 'No products match your filters.',
  },
  productFilters: {
    title: 'Filters',
    sortBy: 'Sort by',
    sortNameAsc: 'Name (A–Z)',
    sortPriceAsc: 'Price (low to high)',
    sortPriceDesc: 'Price (high to low)',
    priceRange: 'Price range',
    minPricePlaceholder: 'Min',
    maxPricePlaceholder: 'Max',
    favoritesOnly: 'Favorites only',
    reset: 'Reset',
    apply: 'Apply',
  },
  order: {
    title: 'Current Order',
    itemsSuffix: 'items',
    forPrefix: 'For',
    pickupToday: 'Pickup today',
    subtotal: 'Subtotal',
    deliveryDiscount: 'Delivery discount',
    salesTax: 'Sales tax',
    totalDue: 'Total due',
    holdOrder: 'Hold order',
    printTicket: 'Print ticket',
    chargePrefix: 'Charge',
    empty: 'No items yet — add products to start an order.',
    changeCustomer: 'Add or change customer',
    couponDiscount: 'Coupon',
    removeItem: 'Remove item',
  },
  payment: {
    card: 'Card',
    cash: 'Cash',
    giftCard: 'Gift Card',
  },
  stats: {
    todaysOrders: "Today's Orders",
    revenue: 'Revenue',
    topSeller: 'Top Seller',
    vsYesterday: 'vs yesterday',
    ordersTodaySuffix: 'orders today',
  },
  nav: {
    allProducts: 'All Products',
    bouquets: 'Bouquets',
    singleStems: 'Single Stems',
    arrangements: 'Arrangements',
    plants: 'Plants',
    gifts: 'Gifts',
    seasonal: 'Seasonal',
    orders: 'Orders',
    customers: 'Customers',
    coupons: 'Coupons',
    reports: 'Reports',
    settings: 'Settings',
    collapse: 'Collapse',
    expand: 'Expand',
  },
  ordersPage: {
    title: 'Orders',
    subtitle: 'Track and manage every order across the counter.',
    searchPlaceholder: 'Search by order number or customer...',
    columnOrder: 'Order',
    columnCustomer: 'Customer',
    columnItems: 'Items',
    columnFulfillment: 'Fulfillment',
    columnTotal: 'Total',
    columnStatus: 'Status',
    columnPlaced: 'Placed',
    filterAll: 'All',
    empty: 'No orders match your search.',
  },
  orderStatus: {
    completed: 'Completed',
    pending: 'Pending',
    refunded: 'Refunded',
  },
  customersPage: {
    title: 'Customers',
    subtitle: 'Everyone who has ordered from the shop.',
    searchPlaceholder: 'Search customers...',
    orders: 'orders',
    totalSpent: 'Total spent',
    lastOrder: 'Last order',
    favoriteCategory: 'Favorite category',
    empty: 'No customers match your search.',
    addCustomer: 'Add customer',
    editAction: 'Edit',
    deleteAction: 'Delete',
    rowActionsLabel: 'Customer actions',
  },
  customerFormModal: {
    addTitle: 'Add customer',
    editTitle: 'Edit customer',
    addDescription: 'Add a new customer to the shop directory.',
    editDescription: 'Update this customer’s details.',
    name: 'Full name',
    namePlaceholder: 'e.g. Jamie Lin',
    email: 'Email',
    emailPlaceholder: 'jamie@example.com',
    phone: 'Phone',
    phonePlaceholder: '(555) 123-4567',
    favoriteCategory: 'Favorite category',
    cancel: 'Cancel',
    addSubmit: 'Add customer',
    editSubmit: 'Save changes',
    nameRequired: 'Name is required.',
    emailInvalid: 'Enter a valid email address.',
    phoneRequired: 'Phone number is required.',
  },
  deleteCustomerDialog: {
    title: 'Delete customer?',
    description: 'This removes {name} from the shop directory. This can’t be undone.',
    cancel: 'Cancel',
    confirm: 'Delete',
  },
  couponsPage: {
    title: 'Coupons',
    subtitle: 'Discount codes your team can apply at checkout.',
    searchPlaceholder: 'Search by code or description...',
    addCoupon: 'Add coupon',
    columnCode: 'Code',
    columnDescription: 'Description',
    columnDiscount: 'Discount',
    columnMinSpend: 'Min. spend',
    columnUsage: 'Usage',
    columnExpires: 'Expires',
    columnStatus: 'Status',
    filterAll: 'All',
    empty: 'No coupons match your search.',
    editAction: 'Edit',
    deleteAction: 'Delete',
    rowActionsLabel: 'Coupon actions',
    unlimited: 'Unlimited',
  },
  couponStatus: {
    active: 'Active',
    scheduled: 'Scheduled',
    expired: 'Expired',
  },
  couponFormModal: {
    addTitle: 'Add coupon',
    editTitle: 'Edit coupon',
    addDescription: 'Create a new discount code for the counter.',
    editDescription: 'Update this coupon’s details.',
    code: 'Code',
    codePlaceholder: 'e.g. SPRING25',
    description: 'Description',
    descriptionPlaceholder: 'e.g. $25 off orders over $100',
    discountType: 'Discount type',
    percentage: 'Percentage',
    fixed: 'Fixed amount',
    value: 'Value',
    minSpend: 'Minimum spend (optional)',
    usageLimit: 'Usage limit (optional)',
    expiresAt: 'Expires on',
    status: 'Status',
    cancel: 'Cancel',
    addSubmit: 'Add coupon',
    editSubmit: 'Save changes',
    codeRequired: 'Code is required.',
    descriptionRequired: 'Description is required.',
    valueRequired: 'Enter a value greater than 0.',
    percentageMax: 'Percentage discounts can’t exceed 100.',
    expiresRequired: 'Pick an expiration date.',
  },
  deleteCouponDialog: {
    title: 'Delete coupon?',
    description: 'This removes {code} and it can no longer be applied at checkout.',
    cancel: 'Cancel',
    confirm: 'Delete',
  },
  couponInput: {
    label: 'Coupon code',
    placeholder: 'Enter code',
    apply: 'Apply',
    remove: 'Remove coupon',
  },
  reportsPage: {
    title: 'Reports',
    subtitle: "A look at the shop's performance this week.",
    revenueTrend: 'Revenue, last 7 days',
    topProducts: 'Top products',
    unitsSoldSuffix: 'sold',
    salesByCategory: 'Sales by category',
    topCustomers: 'Top customers',
    ordersSuffix: 'orders',
    orderStatusBreakdown: 'Order status',
    paymentMethodBreakdown: 'Payment methods',
  },
  toasts: {
    customerAdded: '{name} was added to your customers.',
    customerUpdated: '{name}’s details were updated.',
    customerDeleted: '{name} was removed from your customers.',
    orderCharged: 'Order charged — {total}.',
    orderHeld: 'Order held for later.',
    ticketPrinted: 'Ticket sent to the printer.',
    customerRequiredForCharge: 'Add a customer before charging this order.',
    settingsSaved: 'Your settings were saved.',
    couponAdded: '{code} was added to your coupons.',
    couponUpdated: '{code} was updated.',
    couponDeleted: '{code} was deleted.',
    couponApplied: '{code} applied — {amount} off.',
    couponRemoved: 'Coupon removed.',
    itemRemoved: '{name} removed from the order.',
    couponNotFound: 'That coupon code doesn’t exist.',
    couponNotActive: '{code} is {status} and can’t be applied.',
    couponMinSpendNotMet: '{code} requires a minimum spend of {minSpend}.',
    couponLimitReached: '{code} has reached its usage limit.',
  },
  settingsPage: {
    title: 'Settings',
    subtitle: 'Configure your store, payments, and team.',
    storeProfile: 'Store profile',
    storeProfileHint: 'Shown on receipts and the counter header.',
    storeName: 'Store name',
    storeTagline: 'Tagline',
    counterLabel: 'Counter label',
    taxRate: 'Sales tax rate',
    pricing: 'Tax & pricing',
    pricingHint: 'Applied automatically at checkout.',
    paymentMethods: 'Payment methods',
    paymentMethodsHint: 'Choose which tenders the counter accepts.',
    notifications: 'Notifications',
    notificationsHint: 'Decide what the team gets alerted about.',
    notifyNewOrders: 'New orders',
    notifyLowStock: 'Low stock warnings',
    notifyDailySummary: 'Daily summary email',
    team: 'Team',
    teamHint: 'People with access to this counter.',
    saveChanges: 'Save changes',
  },
} as const
